### ISSUE TITLE
Overall metrics?

### ISSUE THREAD

**Issue by pawamoy** [asottile/git-code-debt#100]
I was expecting to see some sort of globally computed technical debt, be it a grade or an estimation of the time needed to fix all the issues. Maybe a ratio as well, something like `time_to_fix / project_age * 100`, or `lines_with_issues / total_lines * 100`. Because right now it's quite difficult to estimate if the overall debt is important or not.

**Comment by asottile** [comment]
While the idea makes sense, in practice it's nearly impossible to calculate.  `git-code-debt` mostly aims to surface graphs of counts and leaves the project management bits up to the consumer.  One way I've seen this work is to use the metrics as a team OKR and work to drive them down over the course of a quarter.

Time estimation is a hard problem :)

The out-of-the-box metrics don't really get into the nitty-gritty of "debt" things, usually those are more interesting and site-specific.

**Comment by asottile** [comment]
ah yeah I meant [Objective + Key Result](https://en.wikipedia.org/wiki/OKR)
