### ISSUE TITLE
Support "View on" link for other providers

### ISSUE THREAD

**Issue by Pawamoy** [asottile/git-code-debt#99]
Let say my configuration has declared my repo to be at `git@my-provider.its-domain.com:my-group/my-repo.git`. Then the "View on" link should be something like `<a href="https://my-provider.its-domain.com/my-group/my-repo/commits/xxxxxxxxx">View on my-provider (its-domain.com)</a>`

(Besides, the current link uses `FIXME_USER` and `FIXME_PROJECT`, is this normal?)

**Comment by asottile** [comment]
The given link is just an example, you can override it with whatever you like (including your example)

**Comment by asottile** [comment]
Simply add / modify `CommitLinks` in metric_config.yaml

**Comment by Pawamoy** [comment]
Ah, this was not mentioned :D Thanks. Consider adding a note about this in the README / docs!
